# Setup
title:               Industrial Organization
tagline:             ''
description:         'IO'
url:                 https://yingzheng-econ.github.io/IO-Course/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ying Zheng
  url:
  email:             yingzheng@ruc.edu.cn

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id:
